name: Build Plugin
on: [ push, pull_request ]
jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4.1.1
      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 8
      - run: mvn --batch-mode --no-transfer-progress -Dgpg.skip clean install
      - run: "integTest/gradlew -p integTest check"
