name: Dependency Submission

on: [ push ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: gradle/actions/dependency-submission@v6
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
